dashboard/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import PasswordChangeView
from .views import CustomPasswordChangeView


urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("administration/", views.administration, name="administration"),
    path('administration/links/', views.social_media_list, name='social_media_list'),
    path('toggle-active/', views.toggle_active, name='toggle_active'),
    path('delete-link/', views.delete_link, name='delete_link'),
    path('reorder-links', views.reorder_links, name='reorder_links'),
    path('administration/links/add/', views.social_media_add, name='social_media_add'),
    path('administration/links/<int:pk>/delete/', views.social_media_delete, name='social_media_delete'),
    path('links/', views.manage_social_media, name='manage_social_media'),
    path('profile/delete/<int:pk>/', views.user_social_media_delete, name='user_social_media_delete'),
    path('profile', views.manage_preferences, name='manage_preferences'),
    path('profile/change-password/', CustomPasswordChangeView.as_view(template_name='dashboard/change_password.html'), name='change_password'),
]

fmartns/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts import views
from django.contrib.auth.views import logout_then_login
from django.views.generic import TemplateView
from django.urls import re_path
from django.views.static import serve
from django.conf import settings

handler404 = 'main.views.page_not_found'

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('logout/', logout_then_login, name='logout'),
    path('accounts/register/', views.register, name='register'),
    path('dashboard/', include('dashboard.urls')),
    path('helloworld/', TemplateView.as_view(template_name="helloworld.html"), name='helloworld'),
    path('vacation/', TemplateView.as_view(template_name="vacation.html"), name='vacation'),
    path('silvia/', TemplateView.as_view(template_name="silvia.html"), name='vacation'),
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]

main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path('u/<str:username>/', views.user_links_page, name='user_links_page'),
    path('contact/', views.contact, name='contact'),
    path('terms/', views.terms, name='terms')
]

dashboard/models.py
from django.db import models
from django.contrib.auth.models import User

class SocialMedia(models.Model):
    name = models.CharField(max_length=100)
    prefix = models.CharField(max_length=100)
    icon = models.FileField(upload_to='static/icons/')

    def __str__(self):
        return self.name

class UserSocialMedia(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    social_media = models.ForeignKey(SocialMedia, on_delete=models.CASCADE)
    username = models.CharField(max_length=100)
    is_active = models.BooleanField(default=True)
    position = models.IntegerField(default=0)

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    job = models.CharField(max_length=100, blank=True)
    is_student = models.BooleanField(default=False)
    primary_color = models.CharField(max_length=7, blank=True)
    secondary_color = models.CharField(max_length=7, blank=True)
    font_color = models.CharField(max_length=7, blank=True)

    def __str__(self):
        return self.user.username

dashboard/forms.py
from django import forms
from .models import SocialMedia, UserSocialMedia, UserProfile
from django.utils.translation import gettext_lazy as _

class SocialMediaForm(forms.ModelForm):
    class Meta:
        model = SocialMedia
        fields = ['name', 'prefix', 'icon']

class UserSocialMediaForm(forms.ModelForm):
    class Meta:
        model = UserSocialMedia
        fields = ['social_media', 'username']

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)
        self.user = user

    def clean(self):
        cleaned_data = super().clean()
        if UserSocialMedia.objects.filter(user=self.user).count() >= 5:
            raise forms.ValidationError(_("You can only select up to 5 social media accounts."))
        return cleaned_data

    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.user = self.user
        if commit:
            instance.save()

        if self.cleaned_data.get('delete'):
            self.cleaned_data['delete'].delete()

        return instance

class UserProfileForm(forms.ModelForm):
    last_name = forms.CharField(required=False)
    primary_color = forms.CharField(widget=forms.TextInput(attrs={'type': 'color'}))
    secondary_color = forms.CharField(widget=forms.TextInput(attrs={'type': 'color'}))
    font_color = forms.CharField(widget=forms.TextInput(attrs={'type': 'color'}))

    class Meta:
        model = UserProfile
        fields = ['first_name', 'last_name', 'job', 'is_student', 'primary_color', 'secondary_color', 'font_color']

dashboard/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import UserSocialMedia, SocialMedia, UserProfile
from .forms import UserSocialMediaForm, SocialMediaForm, UserProfileForm
from django.contrib import messages
from django.http import HttpResponseForbidden
from django.contrib.auth.views import PasswordChangeView
from django.urls import reverse_lazy
from django.utils.translation import gettext as _
from django.utils.translation import gettext_lazy as _
from django.http import JsonResponse
import json  # Adicione esta linha
from django.db import models

@login_required
def dashboard (request):
    return render(request, "dashboard/index.html")

@login_required
def administration(request):
    if not request.user.is_superuser:
        return HttpResponseForbidden()
    return render(request, "dashboard/administration.html")

@login_required
def social_media_list(request):
    if not request.user.is_superuser:
        return HttpResponseForbidden()
    social_medias = SocialMedia.objects.all()
    return render(request, 'dashboard/social_media_list.html', {'social_medias': social_medias})

@login_required
def social_media_add(request):
    if not request.user.is_superuser:
        return HttpResponseForbidden()
    if request.method == 'POST':
        form = SocialMediaForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('social_media_list')
    else:
        form = SocialMediaForm()
    return render(request, 'dashboard/social_media_form.html', {'form': form})

@login_required
def social_media_delete(request, pk):
    if not request.user.is_superuser:
        return HttpResponseForbidden()
    social_media = get_object_or_404(SocialMedia, pk=pk)
    if request.method == 'POST':
        social_media.delete()
        return redirect('social_media_list')
    return render(request, 'dashboard/social_media_confirm_delete.html', {'social_media': social_media})

@login_required
def manage_social_media(request):
    user_social_media = UserSocialMedia.objects.filter(user=request.user)

    if request.method == 'POST':
        form = UserSocialMediaForm(request.POST, user=request.user)
        if form.is_valid():
            form.save()
            return redirect('manage_social_media')
    else:
        form = UserSocialMediaForm(user=request.user)

    return render(request, 'dashboard/links.html', {'user_social_media': user_social_media, 'form': form})

# Adicione estas views para lidar com a ativação/inativação e exclusão
@login_required
def toggle_active(request):
    if request.method == 'POST':
        # Obtém o ID do item a ser ativado ou desativado da solicitação POST
        item_id = request.POST.get('id')

        try:
            # Tenta obter o objeto UserSocialMedia com o ID fornecido
            user_social_media = UserSocialMedia.objects.get(id=item_id)
            
            # Alterna o estado is_active do item
            user_social_media.is_active = not user_social_media.is_active
            user_social_media.save()

            return JsonResponse({'success': True})  # Retorne uma resposta JSON indicando sucesso
        except UserSocialMedia.DoesNotExist:
            return JsonResponse({'error': 'UserSocialMedia item does not exist'})  # Se o item não for encontrado, retorne um erro JSON
    else:
        return JsonResponse({'error': 'Only POST requests are allowed'})  # Se não for uma solicitação POST, retorne um erro JSON

@login_required
def delete_link(request):
    if request.method == 'POST':
        if request.headers.get('x-requested-with') == 'XMLHttpRequest':
            id = request.POST.get('id')
            try:
                user_social_media = UserSocialMedia.objects.get(id=id)
                position = user_social_media.position
                user_social_media.delete()
                
                # Reordenar os itens restantes
                UserSocialMedia.objects.filter(position__gt=position).update(position=models.F('position') - 1)
                
                return JsonResponse({'message': 'Success'})
            except UserSocialMedia.DoesNotExist:
                return JsonResponse({'message': 'Item not found'}, status=404)
    return JsonResponse({'message': 'Failed'}, status=400)

@login_required
def reorder_links(request):
    if request.method == 'POST':
        if request.headers.get('x-requested-with') == 'XMLHttpRequest':
            new_order = request.POST.getlist('draggable-element')
            # Atualizar a ordem no banco de dados
            for index, item_id in enumerate(new_order):
                try:
                    user_social_media = UserSocialMedia.objects.get(id=item_id)
                    user_social_media.position = index
                    user_social_media.save()
                except UserSocialMedia.DoesNotExist:
                    return JsonResponse({'message': 'Item not found'}, status=404)
            return JsonResponse({'message': 'Success'})
    return JsonResponse({'message': 'Failed'}, status=400)

@login_required
def user_links(request):
    user_social_media = UserSocialMedia.objects.filter(user=request.user)
    return render(request, 'user_links.html', {'user_social_media': user_social_media})

@login_required
def user_social_media_delete(request, pk):
    user_social_media = get_object_or_404(UserSocialMedia, pk=pk)
    if request.method == 'POST':
        user_social_media.delete()
        return redirect('manage_social_media')
    return render(request, 'dashboard/user_social_media_confirm_delete.html', {'user_social_media': user_social_media})

@login_required
def manage_preferences(request):
    user_profile, created = UserProfile.objects.get_or_create(user=request.user)
    if request.method == 'POST':
        form = UserProfileForm(request.POST, instance=user_profile)
        if form.is_valid():
            form.save()
            messages.success(request, _('Settings saved successfully!'))
            return redirect('manage_preferences')
    else:
        form = UserProfileForm(instance=user_profile)
    return render(request, 'dashboard/profile.html', {'form': form})

class CustomPasswordChangeView(PasswordChangeView):
    success_url = reverse_lazy('change_password')

    def form_valid(self, form):
        messages.success(self.request, _('Your password has been changed successfully!'))
        return super().form_valid(form)

templates/dashboard/administration.html
{% extends "dashboard/base.html" %}

{% load i18n %}
{% load static %}

{% block meta_tags %}
    <meta name="robots" content="noindex">
    <meta name="description" content="{% trans 'Administrative Panel - fmartns.dev | Technology Portal and Link Portfolio.' %}">
    <meta name="keywords" content="{% trans 'Filipe Martins, fmartns.dev, Dashboard, Access, Security, Authentication, Programming, Development, Python, Technology, Computer Science' %}">

    <!-- Open Graph / Facebook -->
    <meta property="og:type" content="website">
    <meta property="og:title" content="{% trans 'Administrative Panel - fmartns.dev' %}">
    <meta property="og:description" content="{% trans 'Administrative Panel - fmartns.dev | Technology Portal and Link Portfolio.' %}">
    <meta property="og:url" content="https://www.fmartns.dev/accounts/login/">
    <meta property="og:image" content="https://i.imgur.com/VGp4sE3.png">

    <!-- Twitter -->
    <meta property="twitter:card" content="summary_large_image">
    <meta property="twitter:title" content="{% trans 'Administrative Panel - fmartns.dev' %}">
{% endblock %}

{% block title %} {% trans 'Dashboard' %} {% endblock %}

{% block content %}
<h4>{% trans 'Administration Panel' %}</h4>

<div class="row">
  <div class="col-md-6">
    <a href="{% url 'social_media_list' %}">
      <div class="p-3 bg-light">
          <h3><i class="bi bi-archive-fill mr-2"></i>{% trans 'Social Medias' %}</h3>
          <p>{% trans 'Check, add and delete social medias.' %}</p>
      </div>
    </a>
  </div>
</div>
{% endblock %}

templates/dashboard/change_password.html
{% extends "dashboard/base.html" %}

{% load i18n %}
{% load static %}

{% block meta_tags %}
    <meta name="robots" content="noindex">
    <meta name="description" content="{% trans 'Change Password - fmartns.dev | Technology Portal and Link Portfolio.' %}">
    <meta name="keywords" content="{% trans 'Filipe Martins, fmartns.dev, Dashboard, Access, Security, Authentication, Programming, Development, Python, Technology, Computer Science' %}">

    <!-- Open Graph / Facebook -->
    <meta property="og:type" content="website">
    <meta property="og:title" content="{% trans 'Change Password - fmartns.dev' %}">
    <meta property="og:description" content="{% trans 'Change Password - fmartns.dev | Technology Portal and Link Portfolio.' %}">
    <meta property="og:url" content="https://www.fmartns.dev/accounts/login/">
    <meta property="og:image" content="https://i.imgur.com/VGp4sE3.png">

    <!-- Twitter -->
    <meta property="twitter:card" content="summary_large_image">
    <meta property="twitter:title" content="{% trans 'Change Password - fmartns.dev' %}">
{% endblock %}

{% block title %} {% trans 'Dashboard' %} {% endblock %}

{% block content %}
  <h4>{% trans 'Change password' %}</h4>
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <div class="form-group">
        <label for="{{ field.auto_id }}">{{ field.label }}</label>
        <input type="password" id="{{ field.auto_id }}" name="{{ field.html_name }}" value="{{ field.value|default_if_none:'' }}" placeholder="{{ field.label }}" class="form-control" />
        {% for error in field.errors %}
          <div class="error-warn">{{ error }}</div>
        {% endfor %}
      </div>
    {% endfor %}
    {% if messages %}
      {% for message in messages %}
        <div class="error-warn">{{ message }}</div>
      {% endfor %}
    {% endif %}
    <button class="btn btn-primary" type="submit">{% trans 'Save' %}</button>
  </form>
{% endblock %}

templates/dashboard/index.html
{% extends "dashboard/base.html" %}

{% load i18n %}
{% load static %}

{% block meta_tags %}
    <meta name="robots" content="noindex">
    <meta name="description" content="{% trans 'Dashboard - fmartns.dev | Technology Portal and Link Portfolio.' %}">
    <meta name="keywords" content="{% trans 'Filipe Martins, fmartns.dev, Dashboard, Access, Security, Authentication, Programming, Development, Python, Technology, Computer Science' %}">

    <!-- Open Graph / Facebook -->
    <meta property="og:type" content="website">
    <meta property="og:title" content="{% trans 'Dashboard - fmartns.dev' %}">
    <meta property="og:description" content="{% trans 'Dashboard - fmartns.dev | Technology Portal and Link Portfolio.' %}">
    <meta property="og:url" content="https://www.fmartns.dev/accounts/login/">
    <meta property="og:image" content="https://i.imgur.com/VGp4sE3.png">

    <!-- Twitter -->
    <meta property="twitter:card" content="summary_large_image">
    <meta property="twitter:title" content="{% trans 'Dashboard - fmartns.dev' %}">
{% endblock %}

{% block title %} {% trans 'Dashboard' %} {% endblock %}

{% block content %}

<h4>{% trans 'Dashboard' %}</h4>
<p>{% trans 'Hello' %} {{ user.username }}! {% trans 'Welcome again' %}.</p>

<div class="alert alert-success" role="alert">
    <h4 class="alert-heading">Well done!</h4>
    <p>Aww yeah, you successfully read this important alert message. This example text is going to run a bit longer so that you can see how spacing within an alert works with this kind of content.</p>
    <hr>
    <p class="mb-0">Whenever you need to, be sure to use margin utilities to keep things nice and tidy.</p>
</div>

{% endblock %}

templates/dashboard/links.html
{% extends "dashboard/base.html" %}

{% load i18n %}
{% load static %}

{% block meta_tags %}
    <meta name="robots" content="noindex">
    <meta name="description" content="{% trans 'Profile Links - fmartns.dev | Technology Portal and Link Portfolio.' %}">
    <meta name="keywords" content="{% trans 'Filipe Martins, fmartns.dev, Dashboard, Access, Security, Authentication, Programming, Development, Python, Technology, Computer Science' %}">

    <!-- Open Graph / Facebook -->
    <meta property="og:type" content="website">
    <meta property="og:title" content="{% trans 'Profile Links - fmartns.dev' %}">
    <meta property="og:description" content="{% trans 'Profile Links - fmartns.dev | Technology Portal and Link Portfolio.' %}">
    <meta property="og:url" content="https://www.fmartns.dev/accounts/login/">
    <meta property="og:image" content="https://i.imgur.com/VGp4sE3.png">

    <!-- Twitter -->
    <meta property="twitter:card" content="summary_large_image">
    <meta property="twitter:title" content="{% trans 'Profile Links - fmartns.dev' %}">
{% endblock %}

{% block title %} {% trans 'Profile Preferences' %} {% endblock %}

{% block content %}
  <h4>{% trans 'Profile Links' %}</h4>
  {% if form.errors %}
    <div class="alert alert-danger mt-4">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <strong>{% trans 'Error!' %}</strong>
        <ul class="error-warn">
            {% for error in form.non_field_errors %}    
            {{ error }}<br>
            {% endfor %}
            {% for field in form %}
                {% for error in field.errors %}
                {{ field.label }}: {{ error }}<br>
                {% endfor %}
            {% endfor %}
        </ul>
    </div>
  {% endif %}
  <form method="post" class="mt-4">
    {% csrf_token %}
    <div class="form-group">
      <label for="id_social_media">{% trans 'Social Media:' %}</label>
      <select class="form-control" id="id_social_media" name="{{ form.social_media.name }}">
          {% for social_media in form.social_media.field.queryset %}
            <option value="{{ social_media.pk }}" {% if social_media.pk == form.social_media.value %}selected{% endif %}>{{ social_media }}</option>
          {% endfor %}
      </select>
    </div>
    <div class="form-group">
      <label for="id_username">{% trans 'Username:' %}</label>
      <input type="text" class="form-control" id="id_username" name="{{ form.username.name }}" value="" placeholder="{% trans 'Your username' %}">
    </div>
    <button class="btn btn-primary" type="submit">{% trans 'Add' %}</button>
  </form>
  <label class="mt-4">{% trans 'Current links:' %}</label>
  <div class="sortable">
  {% for user_social in user_social_media %}
    <div class="row rounded draggable-element" style="height: 100px; background-color: #f5f5dc; width: 600px; margin: 16px; box-shadow: 0 0 4px rgba(0,0,0,0.2);" data-id="{{ user_social.id }}">
        <div class="col-1 d-flex justify-content-center align-items-center grip-handle" style="cursor: pointer;">
            <i class="bi bi-grip-vertical bi-lg" style="font-size: larger; color: #676B5F;"></i>
        </div>
        <div class="col-8">
            <br>
            <div class="row">
                <strong class="text-dark">{{ user_social.social_media.name }}</strong>
            </div>
            <div>
                <span class="text-body">{{ user_social.social_media.prefix }}{{ user_social.username }}</span>
            </div>
        </div>
        <div class="col-3 d-flex justify-content-center align-items-center">
            <label class="switch" style="margin-top: 10px;">
                <input type="checkbox" {% if user_social.is_active %}checked{% endif %} class="toggle-active" data-id="{{ user_social.id }}">
                <span class="slider round"></span>
            </label>
            <i class="bi bi-trash3-fill trash-icon" data-toggle="modal" data-target="#deleteLink{{ user_social.id }}"></i>
        </div>
    </div>
    <div class="modal fade" id="deleteLink{{ user_social.id }}" tabindex="-1" aria-labelledby="deleteLinkLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteLinkLabel">Excluir link</h5>
                    <button type="button" class="btn-close" data-dismiss="modal" aria-label="Fechar"></button>
                </div>
                <div class="modal-body">
                    <p>Tem certeza que deseja excluir este link permanentemente?</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                    <button type="button" class="btn btn-danger delete-link" data-dismiss="modal" data-id="{{ user_social.id }}">Excluir</button>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

templates/dashboard/profile.html
{% extends "dashboard/base.html" %}

{% load i18n %}
{% load static %}

{% block meta_tags %}
    <meta name="robots" content="noindex">
    <meta name="description" content="{% trans 'Profile Preferences - fmartns.dev | Technology Portal and Link Portfolio.' %}">
    <meta name="keywords" content="{% trans 'Filipe Martins, fmartns.dev, Dashboard, Access, Security, Authentication, Programming, Development, Python, Technology, Computer Science' %}">

    <!-- Open Graph / Facebook -->
    <meta property="og:type" content="website">
    <meta property="og:title" content="{% trans 'Profile Preferences - fmartns.dev' %}">
    <meta property="og:description" content="{% trans 'Profile Preferences - fmartns.dev | Technology Portal and Link Portfolio.' %}">
    <meta property="og:url" content="https://www.fmartns.dev/accounts/login/">
    <meta property="og:image" content="https://i.imgur.com/VGp4sE3.png">

    <!-- Twitter -->
    <meta property="twitter:card" content="summary_large_image">
    <meta property="twitter:title" content="{% trans 'Profile Preferences - fmartns.dev' %}">

    <script src="{% static 'js/sucess.js' %}"></script>
{% endblock %}

{% block title %} {% trans 'Preferences' %} {% endblock %}

{% block content %}
  <h4>{% trans 'Profile Preferences' %}</h4>
  {% for message in messages %}
    <div class="alert alert-success alert-dismissible fade show" role="alert">
      <strong>{% trans 'Sucess! ' %}</strong>{{ message }}
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  {% endfor %}
  <form method="post" class="mt-4">
    {% csrf_token %}
    <div class="form-group">
      <label for="id_first_name">{% trans 'First name:' %}</label> 
      <input type="text" class="form-control" id="id_first_name" name="{{ form.first_name.name }}" value="{{ form.first_name.value }}" placeholder="Filipe">
    </div>

    <div class="form-group">
      <label for="id_last_name">{% trans 'Last name:' %}</label>
      <input type="text" class="form-control" id="id_last_name" name="{{ form.last_name.name }}" value="{{ form.last_name.value }}" placeholder="Martins">
    </div>

    <div class="form-group">
      <label for="id_job">{% trans 'Job:' %}</label>
      <input type="text" class="form-control" id="id_job" name="{{ form.job.name }}" value="{{ form.job.value }}" placeholder="Developer">
    </div>

    <div class="form-group">
      <label for="id_is_student">{% trans 'Is student:' %}</label>
      <select class="form-control" id="id_is_student" name="{{ form.is_student.name }}">
        <option value=True {% if form.is_student.value == True %}selected{% endif %}>{% trans 'Yes' %}</option>
        <option value=False {% if form.is_student.value == False %}selected{% endif %}>{% trans 'No' %}</option>
      </select>
    </div>

    <div class="form-group">
      <label for="id_primary_color">{% trans 'Primary color:' %}</label>
      <input type="color" class="form-control" id="id_primary_color" name="{{ form.primary_color.name }}" value="{{ form.primary_color.value }}">
    </div>

    <div class="form-group">
      <label for="id_secondary_color">{% trans 'Secondary color:' %}</label>
      <input type="color" class="form-control" id="id_secondary_color" name="{{ form.secondary_color.name }}" value="{{ form.secondary_color.value }}">
    </div>

    <div class="form-group">
      <label for="id_font_color">{% trans 'Font color:' %}</label>
      <input type="color" class="form-control" id="id_font_color" name="{{ form.font_color.name }}" value="{{ form.font_color.value }}">
    </div>

    <button class="btn btn-primary" type="submit">{% trans 'Save' %}</button>
  </form>
{% endblock %}

templates/dashboard/social_media_form.html
{% extends "dashboard/base.html" %}

{% load i18n %}
{% load static %}

{% block meta_tags %}
    <meta name="robots" content="noindex">
    <meta name="description" content="{% trans 'Administration | Social Media - fmartns.dev | Technology Portal and Link Portfolio.' %}">
    <meta name="keywords" content="{% trans 'Filipe Martins, fmartns.dev, Dashboard, Access, Security, Authentication, Programming, Development, Python, Technology, Computer Science' %}">

    <!-- Open Graph / Facebook -->
    <meta property="og:type" content="website">
    <meta property="og:title" content="{% trans 'Administration | Social Media - fmartns.dev' %}">
    <meta property="og:description" content="{% trans 'Administration | Social Media - fmartns.dev | Technology Portal and Link Portfolio.' %}">
    <meta property="og:url" content="https://www.fmartns.dev/accounts/login/">
    <meta property="og:image" content="https://i.imgur.com/VGp4sE3.png">

    <!-- Twitter -->
    <meta property="twitter:card" content="summary_large_image">
    <meta property="twitter:title" content="{% trans 'Administration | Social Media - fmartns.dev' %}">
{% endblock %}

{% block title %} {% trans 'Dashboard' %} {% endblock %}

{% block content %}

<p class="directory"><a href="{% url 'administration' %}">{% trans 'Administration' %}</a> > <a href="{% url 'social_media_list' %}"> Social Medias </a> > Add/Edit</p>
<h1>{% if form.instance.pk %}Editar{% else %}Adicionar{% endif %} Rede Social</h1>

<form method="post" class="social-media-form" enctype="multipart/form-data">
  {% csrf_token %}
  <p>
    <label for="id_name">{% trans 'Social Media:' %}</label>
    <input type="text" name="name" maxlength="100" required id="id_name" placeholder="Instagram">
  </p>
  <p>
    <label for="id_prefix">{% trans 'Prefix: ' %}</label>
    <input type="text" name="prefix" maxlength="100" required id="id_prefix" placeholder="https://instagram.com/">
    
    
  </p>
  <p>
    <label for="id_icon">{% trans 'Icon: ' %}</label>
    <input type="file" name="icon" required id="id_icon">
  </p>
  <button class="add-button" type="submit">{% if form.instance.pk %}{% trans 'Save' %}{% else %}{% trans 'Add' %}{% endif %}</button>
</form>

{% endblock %}